protected/modules/admin/controllers/InfoController.php
<?php
class InfoController extends Controller
{
	public function filters()
	{
		return array(
			'accessControl',
		);
	}

	public function accessRules() {
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('basicinfo', 'editabout', 'edittarget'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	public function actionBasicinfo()
	{
		$InfoModel = Info::model()->findbyPk(array('type'=>'info', 'params'=>'siteinfo'));
		$model = new BasicInfoForm();

		if(isset($_POST['BasicInfoForm']))
		{
			$model->attributes=$_POST['BasicInfoForm'];
			
			if($model->validate()){
				$info = array(
						'title'=> $_POST['BasicInfoForm']['title'],
						'tel'=> $_POST['BasicInfoForm']['tel'],
						'fax'=> $_POST['BasicInfoForm']['fax'],
						'email'=> $_POST['BasicInfoForm']['email'],
						'zip'=> $_POST['BasicInfoForm']['zip'],
						'address'=> $_POST['BasicInfoForm']['address'],
					);

				$InfoModel->data = CJSON::encode($info);
				$InfoModel->Update_at = date('Y-m-d H:i:s');

				$InfoModel->save();

				// print_r($InfoModel);
				
				Yii::app()->user->setFlash(
					'contact',
					'網站基本資訊儲存完成'
				);
				
				$this->refresh(); 
			}
			else {
				// $error = $model->getErrors();
				// $error = '系統錯誤！';
			}
		}

		$info = CJSON::decode($InfoModel->data);
		$model->title = $info['title'];
		$model->tel = $info['tel'];
		$model->fax = $info['fax'];
		$model->email = $info['email'];
		$model->zip = $info['zip'];
		$model->address = $info['address'];


		$this->render('basicinfo', array(
			'model' => $model
		));
	}

	public function actionEditabout()
	{
		$model = new AboutForm();

		$aboutModel = Info::model()->findbyPk(array('type'=>'info', 'params'=>'aboutinfo'));

		if(isset($_POST['AboutForm']))
		{
			$model->attributes=$_POST['AboutForm'];
			
			if($model->validate()){
				$info = array(
						'content'=> $_POST['AboutForm']['content'],
					);

				$aboutModel->data = CJSON::encode($info);
				$aboutModel->Update_at = date('Y-m-d H:i:s');

				$aboutModel->save();
				
				// print_r($aboutModel);
				
				Yii::app()->user->setFlash(
					'contact',
					'網站基本資訊儲存完成'
				);
				
				$this->refresh(); 
			}
			else {
				// $error = $model->getErrors();
				// $error = '系統錯誤！';
			}
		}

		$info = CJSON::decode($aboutModel->data);
		$model->content = $info['content'];

		$this->render('editabout', array(
			'model' => $model
		));
	}

	public function actionEdittarget()
	{
		$model = new TargetForm();

		$targetModel = Info::model()->findbyPk(array('type'=>'info', 'params'=>'targetinfo'));

		if(isset($_POST['TargetForm']))
		{
			$model->attributes=$_POST['TargetForm'];
			
			if($model->validate()){
				$info = array(
						'content'=> $_POST['TargetForm']['content'],
					);

				$targetModel->data = CJSON::encode($info);
				$targetModel->Update_at = date('Y-m-d H:i:s');

				$targetModel->save();
				
				// print_r($targetModel);
				
				Yii::app()->user->setFlash(
					'contact',
					'網站基本資訊儲存完成'
				);
				
				$this->refresh(); 
			}
			else {
				// $error = $model->getErrors();
				// $error = '系統錯誤！';
			}
		}

		$info = CJSON::decode($targetModel->data);
		$model->content = $info['content'];

		$this->render('edittarget', array(
			'model' => $model
		));
	}
}

?>

protected/modules/admin/controllers/SuggestController.php
<?php

class SuggestController extends Controller
{
	private $_model;

	public function filters()
	{
		return array(
			'accessControl',
		);
	}
	
	public function accessRules() {
		return array(
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('index', 'view'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}
	
	public function actionIndex()
	{
		$model =new Opinion('search');
		
		$model->unsetAttributes();  
        // print_r($model->search());

        if(isset($_GET['Opinion']))
            $model->attributes=$_GET['Opinion'];

		$this->render('index', array(
			'model'=>$model,
			'data'=>$model->search(),
		));
	}

	public function actionView()
	{
		$this->render('view', array(
			'model' => $this->loadModel(),
		));
	}

	private function loadModel(){
		if($this->_model===null)
		{
			if(isset($_GET['id']))
				$this->_model=Opinion::model()->findbyPk(array('id'=>$_GET['id']));
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}

		return $this->_model;
	}
}

protected/modules/admin/controllers/UserController.php
<?php

class UserController extends Controller {
	public function filters()
	{
		return array(
			'accessControl',
		);
	}
	
	public function accessRules() {
		return array(
			array('allow',
				'actions'=>array('login')
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('logout', 'setnewpassword'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	public function actionLogin() {
		if(!Yii::app()->user->isGuest)
			$this->redirect($this->createUrl('/admin'));

		Yii::import('application.models.forms.LoginForm');

		$model = new LoginForm;
		$formId = 'login-form';

		//var_dump(Yii::app()->user->isGuest );
		if(isset($_POST['LoginForm'])) {
			$model->attributes = $_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login()){
				
				$this->redirect($this->createUrl('/admin'));
			}
		}

		// display the login form
		$this->render('login',array(
			'model' => $model,
		));
	}

	public function actionLogout() {
		Yii::app()->user->logout();
		$this->redirect($this->createUrl('/admin'));
	}

	public function actionSetnewpassword() {
		Yii::import('application.models.forms.SetNewPasswordForm');

		$model = new SetNewPasswordForm;
		$formId = 'forgotpassword-form';

		if (isset($_POST['SetNewPasswordForm']) ){
			$model->attributes = $_POST['SetNewPasswordForm'];
			if($model->validate() && $model->setNewPassword()){
				$this->actionLogout();
			}
		}

		// display the forgotpassword form
		$this->render('setnewpassword',array(
			'model' => $model,
		));
	}
}

protected/modules/admin/views/layouts/login.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Baoyang - Admin</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

</head>
<body>
	<?php echo $content; ?>
</body>

protected/modules/admin/views/layouts/main.php
<?php
	$assetUrl = publish('application.assets');
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Baoyang - Admin</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<!--[if lt IE 9]>
		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

</head>
<?php
//
	$industryArray = array();
	$siteInfoArray = array();
	$suggestArray = array();
	$userArray = array();
	$backupArray = array();

	if(!Yii::app()->user->isGuest){
		$industryArray  = array(
			array('label'=>'產業類別', 'url'=>$this->createUrl('industry/')),
			array('label'=>'產品類型', 'url'=>$this->createUrl('type/')),
			array('label'=>'數據指標', 'url'=>$this->createUrl('technology/')),
			array('label'=>'產品資料', 'url'=>$this->createUrl('itemlist/'))
		);

		$siteInfoArray = array(
			array('label'=>'博洋資訊', 'url'=>$this->createUrl('info/basicinfo')),
			array('label'=>'博洋簡介', 'url'=>$this->createUrl('info/editabout')),
			array('label'=>'博洋願景', 'url'=>$this->createUrl('info/edittarget')),			
		);

		$suggestArray = array(
			array('label'=>'客戶意見', 'url'=>$this->createUrl('suggest/index'))
		);

		$backupArray = array(
			array('label'=>'備份產品資訊', 'url'=>$this->createUrl('backup/sortdb')),
			array('label'=>'備份網站資訊', 'url'=>$this->createUrl('backup/webdb')),
			array('label'=>'備份其他資訊', 'url'=>$this->createUrl('backup/admindb'))
		);

		$userArray = array(
			array('label'=>'變更密碼', 'url'=>$this->createUrl('user/setnewpassword')),
			array('label'=>'登出', 'url'=>$this->createUrl('user/logout'))
		);
	}
?>
<body>
	<?php $this->widget('bootstrap.widgets.BootNavbar', array(
	'fixed'=>true,
	'brand'=>'Baoyang - Admin',
	'brandUrl'=>'default/',
	//'collapse'=>true, // requires bootstrap-responsive.css
	'items'=>array(
		array(
			'class'=>'bootstrap.widgets.BootMenu',
			'items'=>array(
				array('label'=>'產品資料', 'items' => $industryArray),
				array('label'=>'網站資訊', 'items' => $siteInfoArray),
				array('label'=>'客戶意見', 'items' => $suggestArray),
				array('label'=>'備份資料', 'items' => $backupArray),
				array('label'=>'帳戶管理', 'items' => $userArray),
			),
		),
	),
)); ?>

	<div class="content container">
		<div class="breadcrumb-panel">
			<?php if ( !empty($this->breadcrumbs)): ?>
				<?php $this->widget('zii.widgets.CBreadcrumbs', array(
					'homeLink' => false,
					'links'=>$this->breadcrumbs,
					'separator' => '<span class="divider">/</span>',
					'htmlOptions' => array(
						'class' => 'breadcrumb',
					),
				));?>
			<?php endif ?>
		</div>

		<?php echo $content; ?>
	</div>
	<footer style="margin-top:50px;">
		<div class="container">
			<p>&copy; Copyright <?=date('Y')?> Baoyang Lab. All Rights Reserved.</p>
		</div>
	</footer>
</body>
</html>