protected/controllers/ServiceController.php
<?php

class ServiceController extends Controller
{
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}
	
	public function actionIndex()
	{
		$model = new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name= $model->name;
				$tel=$model->tel;
				$email=$model->email;
				$subject=$model->subject;
				$body=$model->body;
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-Type: text/plain; charset=UTF-8";
				
				//mail(Yii::app()->params['adminEmail'],$subject,$model->body, $headers);
				
				
				// $this->SendMail($name, $email, $tel, $subject, $body);
				
				//Send Mail to Guest's email
				if ($email != null) {
					$this->SendMail($email, $name, $email, $tel, $subject, $body, 'guest');
				}

				//Send Mail to Admin's email
				$info = CJSON::decode(Info::model()->getSiteInfo(), true);
				if($info['email'] != null){
					$this->SendMail($info['email'], $name, $email, $tel, $subject, $body, 'service');
				}
				
				
				//Store to Database
				$this->StoreUserSuggest($name, $email, $tel, $subject, $body);
 		
				Yii::app()->user->setFlash(
					'contact',
					'您的意見已經算寄出。在收到您的寶貴意見後，我們將會在第一時間派人專責處理，並儘速與您聯絡。<br>博洋貿易在此感謝您，您們寶貴意見將會是我們持續進度動力。'
				);
				
				$this->refresh();
			}
		}
		$this->render('index', 
			array(
				'model'=>$model
		));
	}

	function SendMail($sendTo, $GuestName, $GuestEmail, $tel, $subject, $body, $model='guest')
	{
		Yii::import('application.extensions.yii-mail.YiiMailMessage');

		$controller = Yii::app()->controller;

		$output = $controller->renderInternal(dirname(__FILE__).'/../views/mails/serviceTemplate.php',array(
			'name'=> $GuestName,
			'email'=> $GuestEmail,
			'tel' => $tel,
			'subject'=> $subject,
			'body'=>$body,
			'model'=>$model
			//'Td'=> Security::encrypt($bill->id),
			//'bill'=>$bill,
		), true);
		

		$message = new YiiMailMessage;
		$message->subject = '博洋貿易客戶服務通知信件';
		$message->setBody(
                    $output,
                    'text/html'
            );
		// $message->setBody('Message content here with HTML', 'text/html');
		$message->addTo($sendTo);
		$message->setFrom(array(Yii::app()->params['noreplyEmail'] => Yii::app()->name ));

		$succ = Yii::app()->mail->send($message);
	}

	function StoreUserSuggest($name, $email, $tel, $subject, $body)
	{
		$model =new Opinion();

		$model->name = $name;
		$model->tel = $tel;
		$model->email = $email;
		$model->title = $subject;
		$model->content = $body;
		$model->Create_at = date('Y-m-d H:i:s');

		$model->save();
	}
}

protected/views/layouts/_footer.php
<div id="footer">
	Copyright &copy; <?php echo date('Y'); ?> by 博洋貿易. All Rights Reserved.
</div><!-- footer -->

protected/views/layouts/_header.php
<?php
	$assetUrl = publish('application.assets');
	$webRoot = Yii::app()->createUrl('/');
?>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Language" content="zh-tw">
	<meta name="language" content="utf-8" />
	<?php if($this->metaTitle): ?>
	<meta name="title" content="<?//=$this->metaTitle?>" />
	<title> <?=$this->metaTitle?> </title>
	<?php endif ?>
	<!-- blueprint CSS framework -->
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php //echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection">
	<![endif]-->

	
	<!-- <link rel="stylesheet" type="text/css" href="<?= Yii::app()->request->baseUrl; ?>/css/mainmenu.css"> -->
	<!-- <link rel="stylesheet" type="text/css" href="<?//= Yii::app()->request->baseUrl;?>/css/screen.css"> -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print">
	
	<link rel="shortcut icon" href="<?=Yii::app()->createUrl('/')?>/favicon.png"/>
</head>
<?php
	Yii::app()->getClientScript()->registerCssFile($assetUrl.'/css/main.css');
	Yii::app()->getClientScript()->registerCssFile($assetUrl.'/css/form.css');
	Yii::app()->getClientScript()->registerCssFile($assetUrl.'/css/screen.css');
?>


	

protected/views/layouts/_top.php
<?php
$assetUrl = publish('application.assets');
$webRoot = Yii::app()->createUrl('/');
?>
<div id="top">
	<!-- header -->
	<div id="header">
		<div id="top_logo"></div>
	</div>
	<!-- end of header -->
	
	<!-- mainmenu -->
	<div id="mainmenu">
		<div style="width:980px; margin:0 auto;">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'關於博洋', 'url'=>array('/site/index')),
				array('label'=>'產品介紹', 'url'=>array('/product/1')),
				array('label'=>'客戶服務', 'url'=>array('/service/index')),
				// array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				// array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); ?>
		</div>
	</div>
	<!-- end of mainmenu -->
</div>
<?php
Yii::app()->getClientScript()->registerCssFile($assetUrl.'/css/mainmenu.css');
?>

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">
<?php
$assetUrl = publish('application.assets');
$webRoot = Yii::app()->createUrl('/');

$this->renderPartial('//layouts/_header', array());
?>
<body>

<?php
	// top
	$this->renderPartial('//layouts/_top', array());
	// end of top
	// 'Sample post'=>array('post/view', 'id'=>12),
        //'Edit',
?>

<div class="main_container980">
	<div id="breadcrum">
	<?php //if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'homeLink'=>CHtml::link('首頁', Yii::app()->homeUrl),
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php //endif?>
	</div>
</div>
<div class="main_container980" style="background:#ffffff;">
	<div id="main_content">
		<div id="left_content">
		
		<?php if($this->summenu):
				$this->widget('application.widgets.SubMenu.SubMenu', array(
					'items' => $this->summenu));
		endif ?>
		<?php
			// $RecommendMenuArray = array(
			// 	array('name'=>'Facebook', 'url'=>''),
			// 	array('name'=>'Twitter', 'url'=>''),
			// 	array('name'=>'Google', 'url'=>''),
			// );
		
			// $this->widget('application.widgets.SliderRecommendMenu.SliderRecommendMenu', array(
			// 	'title'=>'推薦博洋',
			// 	'items' => $RecommendMenuArray,
			// ));
		?>

			<div class="SubMenu" >
				<div class="SubMenu_Header" style="border-bottom:1px dashed #000;">
					<label class="SildeMenu_Label">QR Code</label>
				</div>				
				<div style="margin-top: 10px; text-align: center; ">
					<?php 
					$this->widget('application.widgets.Qrcode.QrcodeWidget', array(
						//'data' => Yii::app()->params['websiteAddress']. Yii::app()->request->baseUrl, 
						'data' => Yii::app()->createAbsoluteUrl('', array(), 'http'), 
						'width' => '120px',
						'height' => '120px'
					));
					?>
				</div>
			</div>	
		</div>
		<div id="right_content">
			<?= $content; ?>
		</div>

		<div class="clear"></div>
	</div>
	
	<div class="clear"></div>
		
</div><!-- page -->

<!-- footer -->
<?= $this->renderPartial('//layouts/_footer')?>
</body>

</html>
<?php
	$widgetAssetsUrl = publish('application.assets');
	Yii::app()->getClientScript()->registerCssFile($widgetAssetsUrl.'/css/main.css');
?>

protected/views/layouts/product.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">
<?php
$assetUrl = publish('application.assets');
$webRoot = Yii::app()->createUrl('/');

$this->renderPartial('//layouts/_header', array());
?>
<body>

<?php
	// top
	$this->renderPartial('//layouts/_top', array());
	// end of top
	// 'Sample post'=>array('post/view', 'id'=>12),
        //'Edit',
?>

<div class="main_container980">
	<div id="breadcrum">
	<?php //if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'homeLink'=>CHtml::link('首頁', Yii::app()->homeUrl),
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php //endif?>
	</div>
</div>
<div class="main_container980" style="background:#ffffff;">
	<div id="main_content">
		<div id="left_content">
		
		<?php 
			$this->widget('application.widgets.SliderIndustryMenu.SliderIndustryMenu', array());
		?>
		<?php
			// $RecommendMenuArray = array(
			// 	array('name'=>'Facebook', 'url'=>''),
			// 	array('name'=>'Twitter', 'url'=>''),
			// 	array('name'=>'Google', 'url'=>''),
			// );
		
			// $this->widget('application.widgets.SliderRecommendMenu.SliderRecommendMenu', array(
			// 	'title'=>'推薦博洋',
			// 	'items' => $RecommendMenuArray,
			// ));
		?>

			<div class="SubMenu" >
				<div class="SubMenu_Header" style="border-bottom:1px dashed #000;">
					<label class="SildeMenu_Label">QR Code</label>
				</div>				
				<div style="margin-top: 10px; text-align: center;">
					<?php 
					$this->widget('application.widgets.Qrcode.QrcodeWidget', array(
						//'data' => Yii::app()->params['websiteAddress']. Yii::app()->request->baseUrl, 
						'data' => Yii::app()->createAbsoluteUrl('', array(), 'http'), 
						'width' => '120px',
						'height' => '120px'
					));
					?>
				</div>
			</div>	
		</div>
		<div id="right_content">
			<?= $content; ?>
		</div>

		<div class="clear"></div>
	</div>
	
	<div class="clear"></div>
		
</div><!-- page -->

<!-- footer -->
<?= $this->renderPartial('//layouts/_footer')?>
</body>

</html>
<?php
	$widgetAssetsUrl = publish('application.assets');
	Yii::app()->getClientScript()->registerCssFile($widgetAssetsUrl.'/css/main.css');
?>